/*
    The code in this file uses open source libraries provided by thecoderscorner

    DO NOT EDIT THIS FILE, IT WILL BE GENERATED EVERY TIME YOU USE THE UI DESIGNER
    INSTEAD EITHER PUT CODE IN YOUR SKETCH OR CREATE ANOTHER SOURCE FILE.

    All the variables you may need access to are marked extern in this file for easy
    use elsewhere.
*/

#ifndef MENU_GENERATED_CODE_H
#define MENU_GENERATED_CODE_H

#include <Arduino.h>
#include <tcMenu.h>
#include <RuntimeMenuItem.h>
#include <Wire.h>
#include <LiquidCrystalIO.h>
#include <IoAbstractionWire.h>
#include "tcMenuLiquidCrystal.h"

void setupMenu();  // forward reference of the menu setup function.
extern const PROGMEM ConnectorLocalInfo applicationInfo;  // defines the app info to the linker.

// Global variables that need exporting

extern LiquidCrystal lcd;
extern LiquidCrystalRenderer renderer;

// Callback functions must always include CALLBACK_FUNCTION after the return type
#define CALLBACK_FUNCTION

// Global Menu Item exports

void CALLBACK_FUNCTION onTimeChanged(int id);
extern TimeFormattedMenuItem menuTime;
void CALLBACK_FUNCTION onDateChanged(int id);
extern DateFormattedMenuItem menuDate;
void CALLBACK_FUNCTION onSetDatetimeChanged(int id);
extern SubMenuItem menuSetDateTime;
void CALLBACK_FUNCTION ondisableIOChanged(int id);
extern ActionMenuItem menuDisableIO;
void CALLBACK_FUNCTION onBacklighChanged(int id);
extern ActionMenuItem menuBacklightOnOff;
void CALLBACK_FUNCTION onSatMsgChanged(int id);
extern ActionMenuItem menuSendSatMsg;
void CALLBACK_FUNCTION onPumpRelayChanged(int id);
extern ActionMenuItem menuTestPumpRelay;
void CALLBACK_FUNCTION onSelftestChanged(int id);
extern SubMenuItem menuSelfTests;
extern BooleanMenuItem menuFuelLow;
extern FloatMenuItem menuBattery;
extern BooleanMenuItem menuTankFull;
void CALLBACK_FUNCTION storageEmptyChanged(int id);
extern BooleanMenuItem menuStorageEmpty;
void CALLBACK_FUNCTION onStorageFullChanged(int id);
extern BooleanMenuItem menuStorageFull;
void CALLBACK_FUNCTION onStatusChanged(int id);
extern SubMenuItem menuStatus;
void CALLBACK_FUNCTION onRetrysChanged(int id);
extern AnalogMenuItem menuRetrys;
void CALLBACK_FUNCTION onStartTimeChanged(int id);
extern AnalogMenuItem menuStartTime;
void CALLBACK_FUNCTION onGeneratorStop(int id);
extern ActionMenuItem menuStop;
void CALLBACK_FUNCTION onGeneratorStart(int id);
extern ActionMenuItem menuStart;
void CALLBACK_FUNCTION onGeneratorRunningChanged(int id);
extern BooleanMenuItem menuRunning;
void CALLBACK_FUNCTION onGeneratorChanged(int id);
extern SubMenuItem menuGenerator;
extern EnumMenuItem menuMode;

#endif // MENU_GENERATED_CODE_H
